name: Quick Test
on: [push, pull_request, workflow_dispatch]
permissions:
  contents: read

jobs:
  tests:
    name: Core Test
    if: "!contains(github.event.head_commit.message, 'ci skip all')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install test requirements
      run: python3 ./devscripts/install_deps.py --include test
    - name: Run tests
      run: |
        python3 -m yt_dlp -v || true
        python3 ./devscripts/run_tests.py core
